version: "2.4"
services:
  solution:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-solution:${VERSION:-latest}
    build:
      context: .
      args:
        BASE_IMAGE: ${SOLUTION_BASE_IMAGE}
        BUILD_IMAGE: ${SOLUTION_BUILD_IMAGE}
        BUILD_CONFIGURATION: ${BUILD_CONFIGURATION}
    scale: 0
  redis:
          image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-redis:${VERSION:-latest}
          build:
            context: ./docker/build/xc-common/redis
            args:
              BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-redis:${SITECORE_VERSION}
  mssql:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}sitecore-xc1-mssql:${VERSION:-latest}
    build:
      context: ./docker/build/xc1-cxa-jss/mssql
      dockerfile: ./standalone/Dockerfile
      args:
        BASE_IMAGE: ${XC_NONPRODUCTION_SITECORE_DOCKER_REGISTRY}xc1-mssql:${XC_PACKAGES_TAG}
        SPE_RESOURCES_IMAGE: ${MODULES_SITECORE_DOCKER_REGISTRY}spe-assets:${SPE_SITECORE_TAG}
        SXA_RESOURCES_IMAGE: ${MODULES_SITECORE_DOCKER_REGISTRY}sxa-xp1-assets:${SXA_SITECORE_TAG}
        HEADLESS_RESOURCES_IMAGE: ${MODULES_SITECORE_DOCKER_REGISTRY}jss-xp1-assets:${JSS_VERSION}
    volumes:
      - ${LOCAL_DATA_PATH}\mssql:c:\data
  solr:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-xc1-solr:${VERSION:-latest}
    build:
      context: ./docker/build/xc1-cxa-jss/solr
      dockerfile: ./standalone/Dockerfile
      args:
        BASE_IMAGE: ${XC_NONPRODUCTION_SITECORE_DOCKER_REGISTRY}sitecore-xc1-solr:${XC_PACKAGES_TAG}
        SXA_RESOURCES_IMAGE: ${SITECORE_MODULE_REGISTRY}sxa-xp1-assets:${SXA_VERSION}
    mem_limit: 1GB
    volumes:
      - ${LOCAL_DATA_PATH}\solr:c:\data
  id:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-id:${VERSION:-latest}
    build:
      context: ./docker/build/xc-common/id
      args:
        BASE_IMAGE: ${XC_SITECORE_DOCKER_REGISTRY}sitecore-xc-id:${XC_PACKAGES_TAG}
  cd:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-xp1-cd:${VERSION:-latest}
    build:
      context: ./docker/build/xc1-cxa-jss/cd
      args:
        BASE_IMAGE: ${XC_SITECORE_DOCKER_REGISTRY}sitecore-xc1-cd:${XC_PACKAGES_TAG}
        SXA_RESOURCES_IMAGE: ${SITECORE_MODULE_REGISTRY}sxa-xp1-assets:${SXA_VERSION}
        TOOLING_IMAGE: ${SITECORE_TOOLS_REGISTRY}sitecore-docker-tools-assets:${TOOLS_VERSION}
        HEADLESS_SERVICES_IMAGE: ${MODULES_SITECORE_DOCKER_REGISTRY}jss-xp1-assets:${JSS_VERSION}
        SOLUTION_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}-solution:${VERSION:-latest}
    depends_on:
      - solution
    volumes:
      - ${LOCAL_DEPLOY_PATH}\website:C:\deploy
      - ${LOCAL_DATA_PATH}\cd:C:\inetpub\wwwroot\App_Data\logs
    entrypoint: powershell -Command "& C:\tools\entrypoints\iis\Development.ps1"
    labels:
      - "traefik.http.routers.cd.entrypoints=websecure"
      - "traefik.http.routers.cd.tls=true"
  cm:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-xp1-cm:${VERSION:-latest}
    build:
      context: ./docker/build/xc1-cxa-jss/cm
      args:
        BASE_IMAGE: ${XC_SITECORE_DOCKER_REGISTRY}sitecore-xc1-cm:${XC_PACKAGES_TAG}
        SPE_RESOURCES_IMAGE: ${SITECORE_MODULE_REGISTRY}spe-assets:${SPE_VERSION}
        SXA_RESOURCES_IMAGE: ${SITECORE_MODULE_REGISTRY}sxa-xp1-assets:${SXA_VERSION}
        TOOLING_IMAGE: ${SITECORE_TOOLS_REGISTRY}sitecore-docker-tools-assets:${TOOLS_VERSION}
        HEADLESS_SERVICES_IMAGE: ${MODULES_SITECORE_DOCKER_REGISTRY}jss-xp1-assets:${JSS_VERSION}
        MANAGEMENT_SERVICES_IMAGE: ${SITECORE_MODULE_REGISTRY}sitecore-management-services-xp1-assets:${MS_VERSION}
        SOLUTION_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}-solution:${VERSION:-latest}
    depends_on:
      - solution
    volumes:
      - ${LOCAL_DEPLOY_PATH}\website:C:\deploy
      - ${LOCAL_DATA_PATH}\cm:C:\inetpub\wwwroot\App_Data\logs
    entrypoint: powershell -Command "& C:\tools\entrypoints\iis\Development.ps1"
  engine-authoring:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-sitecore-xc-engine:${VERSION:-latest}
    build:
      context: ./docker/build/xc-common/engine
      args:
        BASE_IMAGE: ${XC_SITECORE_DOCKER_REGISTRY}sitecore-xc-engine:${XC_PACKAGES_TAG}
        SOLUTION_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}-solution:${VERSION:-latest}
    depends_on:
      - solution
    volumes: 
      - ${LOCAL_DEPLOY_PATH}\website:C:\deploy
      - ${LOCAL_DATA_PATH}\engine:C:\engine
  engine-shops:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-sitecore-xc-engine:${VERSION:-latest}
  engine-minions:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-sitecore-xc-engine:${VERSION:-latest}
  engine-ops:
     image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-sitecore-xc-engine:${VERSION:-latest}
  cortexprocessing:
    scale: 0
  cortexreporting:
    scale: 0
  xdbautomation:
    scale: 0
  xdbautomationrpt:
    scale: 0
  xdbautomationworker:
    scale: 0
  cortexprocessingworker:
    scale: 0
